### ISSUE TITLE
Split the repo in two

### ISSUE THREAD

**Issue by sunker** [grafana/grafana-aws-sdk#26]
It makes no sense to have both frontend and backend code in this repo since they don't share code, settings or version numbers. We should therefore move the frontend code and frontend tooling to a new repo - grafana-aws-sdk-js (or something). The backend code can be kept in this repo, but the repo should be renamed to grafana-aws-sdk-go.

Somewhat related to https://github.com/grafana/grafana-aws-sdk/issues/27.

**Comment by sunker** [comment]
Yep that's totally fine!

**Comment by ryantxu** [comment]
I suppose it is fine -- and we are already dealing with a mass of repos, so :man_shrugging: 
 
the fact that they don't share any code is a bit orthogonal to the fact that both projects are used together.  The frontend+backend need to work with and produce objects that work together.

Is there something I am not thinking of that makes this actually better to have managed in two places rather than one?

**Comment by andresmgot** [comment]
> Is there something I am not thinking of that makes this actually better to have managed in two places rather than one?

Replied at https://github.com/grafana/grafana-aws-sdk/pull/35#issuecomment-963908997.
